/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.valdezchavez.eje02.views;

import io.valdezchavez.eje02.controllers.EmpleadoController;
import io.valdezchavez.eje02.domain.Empleado;
import io.valdezchavez.eje02.exceptions.InvalidDataEmpleadoException;
import io.valdezchavez.eje02.util.Constantes;
import io.valdezchavez.eje02.util.Validator;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Christian
 */
public class EmpleadoView extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form EmpleadoView
     */
    public EmpleadoView() {
        // Selecciona por el metodo por el cual se desea trabajar
        Constantes.FACTORYSERVICE = Constantes.STM;
        initComponents();
        this.jtblresult
                .setModel(new DefaultTableModel(
                        new Object[][]{},
                        new String[]{"ID", "NOMBRES", "APELLIDOS", "REMUNERACION", "EDAD"
                        }
                ));
        listEmpleados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        txtnombresI = new javax.swing.JTextField();
        txtapellidosI = new javax.swing.JTextField();
        txtremuneracionI = new javax.swing.JTextField();
        txtedadI = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnombresU = new javax.swing.JTextField();
        txtapellidosU = new javax.swing.JTextField();
        txtremuneracionU = new javax.swing.JTextField();
        txtedadU = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtbuscarU = new javax.swing.JTextField();
        btnbuscarU = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtbuscarD = new javax.swing.JTextField();
        btnbuscarD = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblnombres = new javax.swing.JLabel();
        lblapellidos = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblRemuneracion = new javax.swing.JLabel();
        lbledad = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnope1 = new javax.swing.JButton();
        btnope2 = new javax.swing.JButton();
        btnope3 = new javax.swing.JButton();
        btnope4 = new javax.swing.JButton();
        btnope5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblresult = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombres");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Remuneración");

        jLabel4.setText("Edad");

        btnInsert.setText("Crear Nuevo Empleado");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtapellidosI))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtnombresI, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtremuneracionI)
                    .addComponent(txtedadI, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addContainerGap(535, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInsert)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtnombresI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtremuneracionI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtapellidosI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtedadI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnInsert)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agreagar", jPanel2);

        jLabel5.setText("Nombres");

        jLabel6.setText("Apellidos");

        jLabel7.setText("Remuneración");

        jLabel8.setText("Edad");

        btnupdate.setText("Modificar Empleado");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jLabel9.setText("ID Empleado");

        btnbuscarU.setText("Buscar");
        btnbuscarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbuscarU, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscarU)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtapellidosU))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtnombresU, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtremuneracionU)
                            .addComponent(txtedadU, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 392, Short.MAX_VALUE)
                        .addComponent(btnupdate)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtbuscarU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarU))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnupdate)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(txtnombresU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtremuneracionU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(txtapellidosU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtedadU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
        );

        jTabbedPane1.addTab("Actualizar", jPanel3);

        jLabel10.setText("ID Empleado");

        btnbuscarD.setText("Buscar");
        btnbuscarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarDActionPerformed(evt);
            }
        });

        jLabel11.setText("Nombres");

        jLabel12.setText("Apellidos");

        lblnombres.setText("jLabel13");

        lblapellidos.setText("jLabel13");

        jLabel13.setText("Remuneración");

        jLabel14.setText("Edad");

        lblRemuneracion.setText("jLabel15");

        lbledad.setText("jLabel15");

        btnDelete.setText("Eliminar Empleado");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbuscarD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscarD))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lblnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(lblapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbledad)
                    .addComponent(lblRemuneracion))
                .addContainerGap(579, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtbuscarD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarD))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblnombres)
                    .addComponent(jLabel13)
                    .addComponent(lblRemuneracion))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblapellidos)
                    .addComponent(jLabel14)
                    .addComponent(lbledad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Eliminar", jPanel4);

        btnope1.setText("Mostrar el Ultimo Empleado, El Mayor");
        btnope1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnope1ActionPerformed(evt);
            }
        });

        btnope2.setText("Validar que todos Ganen más de 1850");
        btnope2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnope2ActionPerformed(evt);
            }
        });

        btnope3.setText("Todos los Empleados que ganan más 1100 < 38 años y Apellidos no empiece con \"C\"");
        btnope3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnope3ActionPerformed(evt);
            }
        });

        btnope4.setText("Sueldo Bruto Anual de Cada Empleado");
        btnope4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnope4ActionPerformed(evt);
            }
        });

        btnope5.setText("Calcular el Promedio de Sueldo mayores 35 años");
        btnope5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnope5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnope1)
                        .addGap(18, 18, 18)
                        .addComponent(btnope2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnope3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnope4)
                        .addGap(18, 18, 18)
                        .addComponent(btnope5)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnope1)
                    .addComponent(btnope2)
                    .addComponent(btnope3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnope4)
                    .addComponent(btnope5))
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Operaciones", jPanel5);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        jtblresult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblresult);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        try {
            if (!Validator.onlyNumber(txtremuneracionI.getText())) {
                JOptionPane.showMessageDialog(this, "Remuneracion Invalidad, solo numeros de 4 digitos");
                return;
            }
            Empleado emp = new Empleado();
            emp.setNombres(txtnombresI.getText());
            emp.setApellidos(txtapellidosI.getText());
            emp.setRemuneracion(Double.parseDouble(txtremuneracionI.getText()));
            emp.setEdad(Integer.parseInt(txtedadI.getText()));
            if (emp.getEdad() < 18) {
                throw new InvalidDataEmpleadoException();
            }
            if (new EmpleadoController().insert(emp)) {
                JOptionPane.showMessageDialog(this, "Cliente Ingresado Correctamente!");
                listEmpleados();
            } else {
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error");
            }
        } catch (SQLException | InvalidDataEmpleadoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Alerta", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnbuscarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarUActionPerformed
        try {
            Empleado emp =  new EmpleadoController().getEntity(Integer.parseInt(txtbuscarU.getText()));
            if (emp == null)
            {
                JOptionPane.showMessageDialog(this, "No se ha encontrado Resultados");
                return;
            }
            txtnombresU.setText(emp.getNombres());
            txtapellidosU.setText(emp.getApellidos());
            txtremuneracionU.setText(""+emp.getRemuneracion().intValue());
            txtedadU.setText(""+emp.getEdad());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
    }//GEN-LAST:event_btnbuscarUActionPerformed

    private void btnbuscarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarDActionPerformed
        try {
            Empleado emp =  new EmpleadoController().getEntity(Integer.parseInt(txtbuscarD.getText()));
            if (emp == null)
            {
                JOptionPane.showMessageDialog(this, "No se ha encontrado Resultados");
                return;
            }
            lblnombres.setText(emp.getNombres());
            lblapellidos.setText(emp.getApellidos());
            lblRemuneracion.setText(""+emp.getRemuneracion());
            lbledad.setText(""+emp.getEdad());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnbuscarDActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {
            if (!Validator.onlyNumber(txtremuneracionU.getText())) {
                JOptionPane.showMessageDialog(this, "Remuneracion Invalidad, solo numeros de 4 digitos");
                return;
            }
            Empleado emp = new Empleado();
            emp.setNombres(txtnombresU.getText());
            emp.setApellidos(txtapellidosU.getText());
            emp.setRemuneracion(Double.parseDouble(txtremuneracionU.getText()));
            emp.setEdad(Integer.parseInt(txtedadU.getText()));
            emp.setId(Integer.parseInt(txtbuscarU.getText()));
            if (emp.getEdad() < 18) {
                throw new InvalidDataEmpleadoException();
            }
            if (new EmpleadoController().update(emp)) {
                JOptionPane.showMessageDialog(this, "Cliente Modificado Correctamente!");
                listEmpleados();
            } else {
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error");
            }
        } catch (SQLException | InvalidDataEmpleadoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            Empleado emp = new Empleado();
            emp.setId(Integer.parseInt(txtbuscarD.getText()));
            if (new EmpleadoController().delete(emp)) {
                JOptionPane.showMessageDialog(this, "Cliente eliminado Correctamente!");
                listEmpleados();
            } else {
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnope1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnope1ActionPerformed
        try {
            List<Empleado> emp = new ArrayList<>();
            emp.add(new EmpleadoController().getLastElement());
            DefaultTableModel dtm = new DefaultTableModel(
                        new Object[][]{},
                        new String[]{"ID", "NOMBRES", "APELLIDOS", "REMUNERACION", "EDAD"
                        });
            emp.forEach((e) -> {
                dtm.addRow(new Object[]{e.getId(), e.getNombres(), e.getApellidos(), e.getRemuneracion(), e.getEdad()});
            });
            this.jtblresult.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnope1ActionPerformed

    private void btnope2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnope2ActionPerformed
        try {
            boolean state = new EmpleadoController().todosMayor1850();
            if (state){
                JOptionPane.showMessageDialog(this, "Todos los empleados Ganan más 1850 | VERDADERO");
            }else{
                JOptionPane.showMessageDialog(this, "NO todos los empleados Ganan más 1850 | FALSO");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnope2ActionPerformed

    private void btnope3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnope3ActionPerformed
        try {
            List<Empleado> emp = new EmpleadoController().sueldoMayoryEdadMenoryApellidoNOC();
            DefaultTableModel dtm = new DefaultTableModel(
                        new Object[][]{},
                        new String[]{"ID", "NOMBRES", "APELLIDOS", "REMUNERACION", "EDAD"
                        });
            emp.forEach((e) -> {
                dtm.addRow(new Object[]{e.getId(), e.getNombres(), e.getApellidos(), e.getRemuneracion(), e.getEdad()});
            });
            this.jtblresult.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnope3ActionPerformed

    private void btnope4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnope4ActionPerformed
        try {
            List<Empleado> emp = new EmpleadoController().sueldoBruto();
            DefaultTableModel dtm = new DefaultTableModel(
                        new Object[][]{},
                        new String[]{"ID", "NOMBRES", "APELLIDOS", "EDAD", "REMUNERACION", "SUELDO BRUTO"
                        });
            emp.forEach((e) -> {
                dtm.addRow(new Object[]{e.getId(), e.getNombres(), e.getApellidos(), e.getEdad(), e.getRemuneracion(), e.getBruto()});
            });
            this.jtblresult.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnope4ActionPerformed

    private void btnope5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnope5ActionPerformed
        try {
            double promedio = new EmpleadoController().sueldoPromedio();
            JOptionPane.showMessageDialog(this, "EL SUELDO PROMEDIO DE MAYORES QUE 35 AÑos es: " + promedio);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnope5ActionPerformed

    
    private void listEmpleados()
    {
        try {
         List<Empleado> emp = new EmpleadoController().getEntities();
         DefaultTableModel dtm = new DefaultTableModel(
                        new Object[][]{},
                        new String[]{"ID", "NOMBRES", "APELLIDOS", "REMUNERACION", "EDAD"
                        });
            for (Empleado e : emp) {
                dtm.addRow(new Object[]{e.getId(), e.getNombres(), e.getApellidos(), e.getRemuneracion(), e.getEdad()});
            }
            this.jtblresult.setModel(dtm);
        } catch (Exception e) {
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnbuscarD;
    private javax.swing.JButton btnbuscarU;
    private javax.swing.JButton btnope1;
    private javax.swing.JButton btnope2;
    private javax.swing.JButton btnope3;
    private javax.swing.JButton btnope4;
    private javax.swing.JButton btnope5;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtblresult;
    private javax.swing.JLabel lblRemuneracion;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lbledad;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JTextField txtapellidosI;
    private javax.swing.JTextField txtapellidosU;
    private javax.swing.JTextField txtbuscarD;
    private javax.swing.JTextField txtbuscarU;
    private javax.swing.JTextField txtedadI;
    private javax.swing.JTextField txtedadU;
    private javax.swing.JTextField txtnombresI;
    private javax.swing.JTextField txtnombresU;
    private javax.swing.JTextField txtremuneracionI;
    private javax.swing.JTextField txtremuneracionU;
    // End of variables declaration//GEN-END:variables

}
